version: '3'
services:
  web:
    build: .
    environment:
      S3_ENDPOINT: "minio:9000"
      S3_ACCESS_KEY_ID: "minioadmin"
      S3_SECRET_ACCESS_KEY: "minioadmin"
      S3_BUCKET_NAME: "dublinbikeparking-images"
      S3_USE_SSL: "false"
    links:
      - minio
    ports:
      - "3000:3000"
  minio:
    image: "minio/minio"
    command: "server /data"
    ports:
      - "9000:9000"
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb -p myminio/dublinbikeparking-images;
      exit 0;
      "