kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "dublinbikeparking.fullname" . }}
  namespace: default
  labels:
    {{- include "dublinbikeparking.labels" . | nindent 4 }}

spec:
  rules:
    - host: dublinbikeparking.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dublinbikeparking.fullname" . }}
                port:
                  name: http
    - host: www.dublinbikeparking.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dublinbikeparking.fullname" . }}
                port:
                  name: http
