version: 2.1

orbs:
  golangci-lint: timakin/golangci-lint@0.1.1
  heroku: circleci/heroku@1.2.6

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: katiechapman/dublinbikeparking
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  test:
    docker:
      # specify the version
      - image: cimg/go:1.21

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-pkg-cache

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...

      - run: go test -v ./...

      - save_cache: # Store cache in the /go/pkg directory
          key: v2-pkg-cache
          paths:
            - "/go/pkg"
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: dublinbikeparking

workflows:
  version: 2
  build-main:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
